{"uid":"602883c752746cbe","name":"User sends a correct data into the form","fullName":"ui_tests.test_form_from_main_page.TestMainPageForm#test_positive_form_data","historyId":"350f59d9efd3056da7a4a44ebe3ee198","time":{"start":1670791303241,"stop":1670791311736,"duration":8495},"description":"User is scrolling to the bottom and sends correct data","descriptionHtml":"<p>User is scrolling to the bottom and sends correct data</p>\n","status":"failed","statusMessage":"AssertionError: Not success popup presented","statusTrace":"self = <ui_tests.test_form_from_main_page.TestMainPageForm object at 0x7f11852b8790>\nbrowser = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"e31c0a7d-9354-4884-8aa8-e69802ca380a\")>\npositive_data_case = [(('name', 'name'), 'test_user'), (('name', 'email'), 'test@fojin.tech'), (('name', 'phone'), '12345678901'), (('name', 'about'), 'some useless information')]\n\n    @allure.title('User sends a correct data into the form')\n    @severity(severity_level.CRITICAL)\n    @allure.feature('User sends correct data')\n    @allure.description('User is scrolling to the bottom and sends correct data')\n    def test_positive_form_data(self, browser, positive_data_case: list):\n        \"\"\"\n          Test fills the application with correct data and checks the popup answer\n        \"\"\"\n        page = MainPage(browser, self.url)\n        page.open()\n        for data in positive_data_case:\n            page.input_data_to_form(data)\n        page.scroll_to_and_click_element(FormLocators.SEND_BUTTON)\n        page.expl_wait_for_elem_visibility(FormLocators.POPUP)\n>       page.check_popup_is_presented(FormLocators.POPUP)\n\nui_tests/test_form_from_main_page.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <ui_tests.pages.main_page.MainPage object at 0x7f117faab910>\nlocator = ('css selector', '#form > div > div > div')\n\n    def check_popup_is_presented(self, locator: tuple):\n        \"\"\"\n        Test checks that success message appears\n        \"\"\"\n        popup = self.browser.find_element(*locator)\n        print(popup.text)\n>       assert popup.is_displayed(), 'Not success popup presented'\nE       AssertionError: Not success popup presented\n\nui_tests/pages/main_page.py:80: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":2,"retriesStatusChange":false,"beforeStages":[{"name":"browser","time":{"start":1670791299880,"stop":1670791303241,"duration":3361},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"test_failed_check","time":{"start":1670791299880,"stop":1670791299880,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"positive_data_case","time":{"start":1670791303241,"stop":1670791303241,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is scrolling to the bottom and sends correct data","status":"failed","statusMessage":"AssertionError: Not success popup presented","statusTrace":"self = <ui_tests.test_form_from_main_page.TestMainPageForm object at 0x7f11852b8790>\nbrowser = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"e31c0a7d-9354-4884-8aa8-e69802ca380a\")>\npositive_data_case = [(('name', 'name'), 'test_user'), (('name', 'email'), 'test@fojin.tech'), (('name', 'phone'), '12345678901'), (('name', 'about'), 'some useless information')]\n\n    @allure.title('User sends a correct data into the form')\n    @severity(severity_level.CRITICAL)\n    @allure.feature('User sends correct data')\n    @allure.description('User is scrolling to the bottom and sends correct data')\n    def test_positive_form_data(self, browser, positive_data_case: list):\n        \"\"\"\n          Test fills the application with correct data and checks the popup answer\n        \"\"\"\n        page = MainPage(browser, self.url)\n        page.open()\n        for data in positive_data_case:\n            page.input_data_to_form(data)\n        page.scroll_to_and_click_element(FormLocators.SEND_BUTTON)\n        page.expl_wait_for_elem_visibility(FormLocators.POPUP)\n>       page.check_popup_is_presented(FormLocators.POPUP)\n\nui_tests/test_form_from_main_page.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <ui_tests.pages.main_page.MainPage object at 0x7f117faab910>\nlocator = ('css selector', '#form > div > div > div')\n\n    def check_popup_is_presented(self, locator: tuple):\n        \"\"\"\n        Test checks that success message appears\n        \"\"\"\n        popup = self.browser.find_element(*locator)\n        print(popup.text)\n>       assert popup.is_displayed(), 'Not success popup presented'\nE       AssertionError: Not success popup presented\n\nui_tests/pages/main_page.py:80: AssertionError","steps":[],"attachments":[{"uid":"87a6b88e0811ed70","name":"log","source":"87a6b88e0811ed70.txt","type":"text/plain","size":3356},{"uid":"8df42ebf0ddd32d6","name":"stdout","source":"8df42ebf0ddd32d6.txt","type":"text/plain","size":3},{"uid":"3e7e5de54ad6ce06","name":"stderr","source":"3e7e5de54ad6ce06.txt","type":"text/plain","size":766}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"browser::0","time":{"start":1670791311740,"stop":1670791312704,"duration":964},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"test_failed_check::0","time":{"start":1670791312704,"stop":1670791312710,"duration":6},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50149): Max retries exceeded with url: /session/e31c0a7d-9354-4884-8aa8-e69802ca380a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fd30610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/fojin_site/fojin_site/conftest.py\", line 61, in test_failed_check\n    screenshot(driver, request.node.nodeid)\n  File \"/home/runner/work/fojin_site/fojin_site/conftest.py\", line 66, in screenshot\n    allure.attach(browser.get_screenshot_as_png(), name=f\"Screenshot fail_{name}\",\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 965, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 977, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"labels":[{"name":"feature","value":"User sends correct data"},{"name":"severity","value":"critical"},{"name":"parentSuite","value":"ui_tests"},{"name":"suite","value":"test_form_from_main_page"},{"name":"subSuite","value":"TestMainPageForm"},{"name":"host","value":"fv-az405-431"},{"name":"thread","value":"3289-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"ui_tests.test_form_from_main_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'firefox'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"422c525305d7c1fb","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670791290530,"stop":1670791298998,"duration":8468}},{"uid":"86002d60fff9c064","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670791277362,"stop":1670791285944,"duration":8582}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":7,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":10},"items":[{"uid":"1b6cc1308f6835b3","reportUrl":"https://vadim-makarov.github.io/fojin_site/46//#testresult/1b6cc1308f6835b3","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670788688940,"stop":1670788697247,"duration":8307}},{"uid":"890d2a1218f82ab0","reportUrl":"https://vadim-makarov.github.io/fojin_site/45//#testresult/890d2a1218f82ab0","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670787916925,"stop":1670787925677,"duration":8752}},{"uid":"7be8033543e9e1ea","reportUrl":"https://vadim-makarov.github.io/fojin_site/44//#testresult/7be8033543e9e1ea","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670786733634,"stop":1670786740582,"duration":6948}},{"uid":"522cc2f10309348c","reportUrl":"https://vadim-makarov.github.io/fojin_site/43//#testresult/522cc2f10309348c","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670772058366,"stop":1670772068458,"duration":10092}},{"uid":"e54ff28c95445f1b","reportUrl":"https://vadim-makarov.github.io/fojin_site/42//#testresult/e54ff28c95445f1b","status":"broken","statusDetails":"selenium.common.exceptions.ElementClickInterceptedException: Message: Element <div class=\"sc-63050886-2 gpFpVi\"> is not clickable at point (1074,654) because another element <div class=\"sc-2a084499-1 kRPMVF\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:281:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:160:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:119:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:198:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:86:31","time":{"start":1670770114312,"stop":1670770119760,"duration":5448}},{"uid":"f4ed4a12e7f9ff6f","reportUrl":"https://vadim-makarov.github.io/fojin_site/41//#testresult/f4ed4a12e7f9ff6f","status":"passed","time":{"start":1670706749771,"stop":1670706755905,"duration":6134}},{"uid":"e205a7ec67641e50","reportUrl":"https://vadim-makarov.github.io/fojin_site/40//#testresult/e205a7ec67641e50","status":"broken","statusDetails":"selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None\nMessage: Dismissed user prompt dialog: This site is asking you to sign in.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nUnexpectedAlertOpenError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:487:5\nGeckoDriver.prototype._handleUserPrompts@chrome://remote/content/marionette/driver.sys.mjs:2695:13","time":{"start":1670703984970,"stop":1670703985542,"duration":572}},{"uid":"57ea428535456bd6","reportUrl":"https://vadim-makarov.github.io/fojin_site/39//#testresult/57ea428535456bd6","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670701998463,"stop":1670702006986,"duration":8523}},{"uid":"276864e641255373","reportUrl":"https://vadim-makarov.github.io/fojin_site/37//#testresult/276864e641255373","status":"failed","statusDetails":"AssertionError: Not success popup presented","time":{"start":1670701848375,"stop":1670701856958,"duration":8583}}]},"tags":[]},"source":"602883c752746cbe.json","parameterValues":["'firefox'"]}