WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239179550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a725a25f-0121-42c2-8d55-adb84cbdf784/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523917a250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a725a25f-0121-42c2-8d55-adb84cbdf784/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239178d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a725a25f-0121-42c2-8d55-adb84cbdf784/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52392c5910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/01abe4a7-0a9a-49dd-b771-93d0452f5e0e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239278590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/01abe4a7-0a9a-49dd-b771-93d0452f5e0e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523927b090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/01abe4a7-0a9a-49dd-b771-93d0452f5e0e/screenshot