WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11851cec90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/734864b5-3067-413d-8a36-401f0bf4819a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11851d44d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/734864b5-3067-413d-8a36-401f0bf4819a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11851d6fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/734864b5-3067-413d-8a36-401f0bf4819a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fda7310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/472dc10a-ac70-4c08-b70b-3b08e3ddf74e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fda73d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/472dc10a-ac70-4c08-b70b-3b08e3ddf74e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fda4bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/472dc10a-ac70-4c08-b70b-3b08e3ddf74e/screenshot