WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b2e990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/460adb0a-2069-4046-be7c-0e89e24f2c4e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b2e410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/460adb0a-2069-4046-be7c-0e89e24f2c4e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b2f050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/460adb0a-2069-4046-be7c-0e89e24f2c4e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39bae810>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f8d49a2d-506e-4290-a9fc-cac8e9e2f65d/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39bac1d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f8d49a2d-506e-4290-a9fc-cac8e9e2f65d/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39baf990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f8d49a2d-506e-4290-a9fc-cac8e9e2f65d/screenshot