WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523917ac10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ecf03c4-c49b-4380-9aa7-7cd9878df82f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523917aed0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ecf03c4-c49b-4380-9aa7-7cd9878df82f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523917bd10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ecf03c4-c49b-4380-9aa7-7cd9878df82f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523940f250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/95cddacc-01a3-4451-be60-debc8f5519b9/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523940d550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/95cddacc-01a3-4451-be60-debc8f5519b9/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523940ca50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/95cddacc-01a3-4451-be60-debc8f5519b9/screenshot