WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1827a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5743f229-c9b4-46aa-b6c6-c5eae5e9cad4/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1826c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5743f229-c9b4-46aa-b6c6-c5eae5e9cad4/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1a2b190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5743f229-c9b4-46aa-b6c6-c5eae5e9cad4/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1bf9f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b118d4c5-d27d-40e7-9136-0fd2f06ae128/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1ced050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b118d4c5-d27d-40e7-9136-0fd2f06ae128/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1ced390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b118d4c5-d27d-40e7-9136-0fd2f06ae128/screenshot