WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523921a4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cb1570b4-7705-434b-96d5-a55432e87ca2/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523921ae50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cb1570b4-7705-434b-96d5-a55432e87ca2/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239218850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cb1570b4-7705-434b-96d5-a55432e87ca2/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52395251d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/84bf96b9-3e22-41fc-bf2a-54409d2f108b/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239526e10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/84bf96b9-3e22-41fc-bf2a-54409d2f108b/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5239527f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/84bf96b9-3e22-41fc-bf2a-54409d2f108b/screenshot