WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a2fc7110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1aadf459-a94f-48ae-a015-a6632f28be73/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a2fbfe50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1aadf459-a94f-48ae-a015-a6632f28be73/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a2fccd90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1aadf459-a94f-48ae-a015-a6632f28be73/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1b25f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8e503e5c-1478-404b-b221-be90c961b86f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1b26210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8e503e5c-1478-404b-b221-be90c961b86f/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1b26a50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8e503e5c-1478-404b-b221-be90c961b86f/screenshot