WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52391de350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d7b1af1a-ffa1-4301-973c-87ed22938fec/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52391df050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d7b1af1a-ffa1-4301-973c-87ed22938fec/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52391dca50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d7b1af1a-ffa1-4301-973c-87ed22938fec/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523938ee10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/623e0180-cc47-4241-8466-3cc4d98ec7a9/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523938ead0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/623e0180-cc47-4241-8466-3cc4d98ec7a9/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f523a867cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/623e0180-cc47-4241-8466-3cc4d98ec7a9/screenshot